name: Deploy to EC2

on:
    push:
        branches: [main]

jobs:
    deploy:
        name: Deploy Fluxa Language API to EC2
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup SSH key
              uses: webfactory/ssh-agent@v0.8.0
              with:
                  ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

            - name: Deploy to EC2
              run: |
                  ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
                    cd ~/fluxa-language-api || git clone https://github.com/secretprojectalice/fluxa-language-api.git && cd ~/fluxa-language-api
                    git pull origin main
                    npm install
                    npm run build
                    echo "NODE_ENV=${{ secrets.NODE_ENV }}" > .env
                    echo "PORT=${{ secrets.PORT }}" > .env
                    echo "FLUXA_UI_APP_URL=${{ secrets.FLUXA_UI_APP_URL }}" > .env
                    echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > .env
                    pm2 restart fluxa-language-api || pm2 start dist/server.js --name "fluxa-language-api"
                    pm2 save
                  EOF
